//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public decimal AnnoucementId { get; set; }
        public string Message { get; set; }
        public Nullable<decimal> DesignationId { get; set; }
        public Nullable<decimal> DepartmentId { get; set; }
        public Nullable<int> DesignationS { get; set; }
        public Nullable<int> DepartmentS { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
