//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.Announcements = new HashSet<Announcement>();
            this.Employees = new HashSet<Employee>();
        }
    
        public decimal DesignationId { get; set; }
        public string DesignationName { get; set; }
        public Nullable<decimal> DepartmentId { get; set; }
    
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
